apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-prereqs
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/clusters/my-cluster/apps-prereqs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system