apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- apps-kustomization.yaml
- apps-prereqs-kustomization.yaml
- image-policy.yaml
- image-repo.yaml
- image-automation.yaml
- rbac-image-toolkit.yaml
- rbac-flux-lease.yaml
