apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-image-toolkit-controller
rules:
- apiGroups: ["image.toolkit.fluxcd.io"]
  resources:
    - imagerepositories
    - imagepolicies
    - imageupdateautomations
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups: ["image.toolkit.fluxcd.io"]
  resources:
    - imagerepositories/status
    - imagepolicies/status
    - imageupdateautomations/status
  verbs:
    - get
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-image-toolkit-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-image-toolkit-controller
subjects:
# grant to the standard controller service accounts (common default names)
- kind: ServiceAccount
  name: image-reflector-controller
  namespace: flux-system
- kind: ServiceAccount
  name: image-automation-controller
  namespace: flux-system
- kind: ServiceAccount
  name: default
  namespace: flux-system