{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
