apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-redis-ns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flask-redis-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- include "flask-redis-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: flask
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        -  name: http
           containerPort: {{ .Values.service.port }}
           protocol: TCP
        env:
        - name: HELLO_MSG
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: HELLO_MSG
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: REDIS_HOST
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: APP_PASSWORD
