{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-redis-app.fullname" . }}
  labels:
    {{- include "flask-redis-app.labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls }}
  tls:
    {{- toYaml $.Values.ingress.tls | nindent 2 }}
  {{- end }}
  rules:
    {{- range $.Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- /* prefer explicit configured service.name if present, else use fullname helper */}}
                {{- with $.Values.service }}
                name: {{ .name | default (include "flask-redis-app.fullname" $) }}
                {{- else }}
                name: {{ include "flask-redis-app.fullname" $ }}
                {{- end }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}